version: "3.7"

services:
  backend:
    image: node:18.12.1
    restart: always
    ports:
      - 80:80
    volumes:
      - ./app:/app
    working_dir: /app
    command:
      - npm
      - run
      - dev